package core

// All the following constants are coming from:
// https://github.com/torvalds/linux/blob/master/include/uapi/linux/devlink.h

const (

	// GenlDevlinkName - GENL_DEVLINK_NAME
	GenlDevlinkName = "devlink"

	// GenlDevlinkVersion - GENL_DEVLINK_VERSION
	GenlDevlinkVersion = 1
)
const (

	// DevlinkAttrBusName - DEVLINK_ATTR_BUS_NAME
	DevlinkAttrBusName = 1

	// DevlinkAttrDevName - DEVLINK_ATTR_DEV_NAME
	DevlinkAttrDevName = 2

	// DevlinkAttrPortIndex - DEVLINK_ATTR_PORT_INDEX
	DevlinkAttrPortIndex = 3

	// DevlinkAttrPortType - DEVLINK_ATTR_PORT_TYPE
	DevlinkAttrPortType = 4

	// DevlinkAttrPortNetdevIfindex - DEVLINK_ATTR_PORT_NETDEV_IFINDEX
	DevlinkAttrPortNetdevIfindex = 6

	// DevlinkAttrPortNetdevName - DEVLINK_ATTR_PORT_NETDEV_NAME
	DevlinkAttrPortNetdevName = 7

	// DevlinkAttrPortIbdevName - DEVLINK_ATTR_PORT_IBDEV_NAME
	DevlinkAttrPortIbdevName = 8

	// DevlinkAttrEswitchMode - DEVLINK_ATTR_ESWITCH_MODE
	DevlinkAttrEswitchMode = 25

	// DevlinkAttrEswitchInlineMode - DEVLINK_ATTR_ESWITCH_INLINE_MODE
	DevlinkAttrEswitchInlineMode = 26

	// DevlinkAttrEswitchEncapMode - DEVLINK_ATTR_ESWITCH_ENCAP_MODE
	DevlinkAttrEswitchEncapMode = 62

	// DevlinkAttrResourceList - DEVLINK_ATTR_RESOURCE_LIST
	DevlinkAttrResourceList = 63 /* nested */

	// DevlinkAttrResource - DEVLINK_ATTR_RESOURCE
	DevlinkAttrResource = 64 /* nested */

	// DevlinkAttrResourceName - DEVLINK_ATTR_RESOURCE_NAME
	DevlinkAttrResourceName = 65 /* string */

	// DevlinkAttrResourceId - DEVLINK_ATTR_RESOURCE_ID
	DevlinkAttrResourceId = 66 /* u64 */

	// DevlinkAttrResourceSize - DEVLINK_ATTR_RESOURCE_SIZE
	DevlinkAttrResourceSize = 67 /* u64 */

	// DevlinkAttrResourceSizeNew - DEVLINK_ATTR_RESOURCE_SIZE_NEW
	DevlinkAttrResourceSizeNew = 68 /* u64 */

	// DEVLINK_ATTR_RESOURCE_SIZE_VALID -
	DEVLINK_ATTR_RESOURCE_SIZE_VALID = 69 /* u8 */

	// DEVLINK_ATTR_RESOURCE_SIZE_MIN -
	DEVLINK_ATTR_RESOURCE_SIZE_MIN = 70 /* u64 */

	// DEVLINK_ATTR_RESOURCE_SIZE_MAX -
	DEVLINK_ATTR_RESOURCE_SIZE_MAX = 71 /* u64 */

	// DEVLINK_ATTR_RESOURCE_SIZE_GRAN -
	DEVLINK_ATTR_RESOURCE_SIZE_GRAN = 72 /* u64 */

	// DEVLINK_ATTR_RESOURCE_UNIT -
	DEVLINK_ATTR_RESOURCE_UNIT = 73 /* u8 */

	// DEVLINK_ATTR_RESOURCE_OCC -
	DEVLINK_ATTR_RESOURCE_OCC = 74 /* u64 */

	// DEVLINK_ATTR_DPIPE_TABLE_RESOURCE_ID -
	DEVLINK_ATTR_DPIPE_TABLE_RESOURCE_ID = 75 /* u64 */

	// DEVLINK_ATTR_DPIPE_TABLE_RESOURCE_UNITS -
	DEVLINK_ATTR_DPIPE_TABLE_RESOURCE_UNITS = 76 /* u64 */

	// DEVLINK_ATTR_PORT_FLAVOUR -
	DEVLINK_ATTR_PORT_FLAVOUR = 77

	// DEVLINK_ATTR_INFO_DRIVER_NAME -
	DEVLINK_ATTR_INFO_DRIVER_NAME = 98

	// DEVLINK_ATTR_INFO_SERIAL_NUMBER -
	DEVLINK_ATTR_INFO_SERIAL_NUMBER = 99

	// DEVLINK_ATTR_INFO_VERSION_FIXED -
	DEVLINK_ATTR_INFO_VERSION_FIXED = 100

	// DEVLINK_ATTR_INFO_VERSION_RUNNING -
	DEVLINK_ATTR_INFO_VERSION_RUNNING = 101

	// DEVLINK_ATTR_INFO_VERSION_STORED -
	DEVLINK_ATTR_INFO_VERSION_STORED = 102

	// DEVLINK_ATTR_INFO_VERSION_NAME -
	DEVLINK_ATTR_INFO_VERSION_NAME = 103

	// DEVLINK_ATTR_INFO_VERSION_VALUE -
	DEVLINK_ATTR_INFO_VERSION_VALUE = 104

	// DEVLINK_ATTR_PORT_PCI_PF_NUMBER -
	DEVLINK_ATTR_PORT_PCI_PF_NUMBER = 127

	// DEVLINK_ATTR_PORT_FUNCTION -
	DEVLINK_ATTR_PORT_FUNCTION = 145

	// DEVLINK_ATTR_PORT_CONTROLLER_NUMBER -
	DEVLINK_ATTR_PORT_CONTROLLER_NUMBER = 150

	// DEVLINK_ATTR_PORT_PCI_SF_NUMBER -
	DEVLINK_ATTR_PORT_PCI_SF_NUMBER = 164
)

const (
	// DEVLINK_CMD_GET -
	DEVLINK_CMD_GET = 1

	// DEVLINK_CMD_PORT_GET -
	DEVLINK_CMD_PORT_GET = 5

	// DEVLINK_CMD_PORT_SET -
	DEVLINK_CMD_PORT_SET = 6

	// DEVLINK_CMD_PORT_NEW -
	DEVLINK_CMD_PORT_NEW = 7

	// DEVLINK_CMD_PORT_DEL -
	DEVLINK_CMD_PORT_DEL = 8

	// DEVLINK_CMD_ESWITCH_GET -
	DEVLINK_CMD_ESWITCH_GET = 29

	// DEVLINK_CMD_ESWITCH_SET -
	DEVLINK_CMD_ESWITCH_SET = 30

	// DEVLINK_CMD_RESOURCE_DUMP -
	DEVLINK_CMD_RESOURCE_DUMP = 36

	// DEVLINK_CMD_PARAM_GET -
	DEVLINK_CMD_PARAM_GET = 38

	// DEVLINK_CMD_PARAM_SET
	DEVLINK_CMD_PARAM_SET = 39

	// DEVLINK_CMD_INFO_GET
	DEVLINK_CMD_INFO_GET = 51
)
const (
	// DEVLINK_ESWITCH_MODE_LEGACY
	DEVLINK_ESWITCH_MODE_LEGACY = 0

	// DEVLINK_ESWITCH_MODE_SWITCHDEV
	DEVLINK_ESWITCH_MODE_SWITCHDEV = 1
)
const (
	// DEVLINK_ESWITCH_INLINE_MODE_NONE
	DEVLINK_ESWITCH_INLINE_MODE_NONE = 0

	// DEVLINK_ESWITCH_INLINE_MODE_LINK
	DEVLINK_ESWITCH_INLINE_MODE_LINK = 1

	// DEVLINK_ESWITCH_INLINE_MODE_NETWORK
	DEVLINK_ESWITCH_INLINE_MODE_NETWORK = 2

	// DEVLINK_ESWITCH_INLINE_MODE_TRANSPORT
	DEVLINK_ESWITCH_INLINE_MODE_TRANSPORT = 3
)
const (
	// DEVLINK_ESWITCH_ENCAP_MODE_NONE
	DEVLINK_ESWITCH_ENCAP_MODE_NONE = 0
	// DEVLINK_ESWITCH_ENCAP_MODE_BASIC
	DEVLINK_ESWITCH_ENCAP_MODE_BASIC = 1
)
const (
	// DEVLINK_PORT_FLAVOUR_PHYSICAL
	DEVLINK_PORT_FLAVOUR_PHYSICAL = 0

	// DEVLINK_PORT_FLAVOUR_CPU
	DEVLINK_PORT_FLAVOUR_CPU = 1

	// DEVLINK_PORT_FLAVOUR_DSA
	DEVLINK_PORT_FLAVOUR_DSA = 2

	// DEVLINK_PORT_FLAVOUR_PCI_PF
	DEVLINK_PORT_FLAVOUR_PCI_PF = 3

	// DEVLINK_PORT_FLAVOUR_PCI_VF
	DEVLINK_PORT_FLAVOUR_PCI_VF = 4

	// DEVLINK_PORT_FLAVOUR_VIRTUAL
	DEVLINK_PORT_FLAVOUR_VIRTUAL = 5

	// DEVLINK_PORT_FLAVOUR_UNUSED
	DEVLINK_PORT_FLAVOUR_UNUSED = 6

	// DEVLINK_PORT_FLAVOUR_PCI_SF
	DEVLINK_PORT_FLAVOUR_PCI_SF = 7
)
const (
	// DEVLINK_PORT_TYPE_NOTSET
	DEVLINK_PORT_TYPE_NOTSET = 0

	// DEVLINK_PORT_TYPE_AUTO
	DEVLINK_PORT_TYPE_AUTO = 1

	// DEVLINK_PORT_TYPE_ETH
	DEVLINK_PORT_TYPE_ETH = 2

	// DEVLINK_PORT_TYPE_IB
	DEVLINK_PORT_TYPE_IB = 3
)
const (
	// DEVLINK_PORT_FUNCTION_ATTR_HW_ADDR
	DEVLINK_PORT_FUNCTION_ATTR_HW_ADDR = 1

	// DEVLINK_PORT_FN_ATTR_STATE
	DEVLINK_PORT_FN_ATTR_STATE = 2

	// DEVLINK_PORT_FN_ATTR_OPSTATE
	DEVLINK_PORT_FN_ATTR_OPSTATE = 3
)
const (
	// DEVLINK_PORT_FN_STATE_INACTIVE
	DEVLINK_PORT_FN_STATE_INACTIVE = 0

	// DEVLINK_PORT_FN_STATE_ACTIVE
	DEVLINK_PORT_FN_STATE_ACTIVE = 1
)
const (
	// DEVLINK_PORT_FN_OPSTATE_DETACHED
	DEVLINK_PORT_FN_OPSTATE_DETACHED = 0

	// DEVLINK_PORT_FN_OPSTATE_ATTACHED
	DEVLINK_PORT_FN_OPSTATE_ATTACHED = 1
)
const (
	// DEVLINK_RESOURCE_UNIT_ENTRY
	DEVLINK_RESOURCE_UNIT_ENTRY uint8 = 0
)
