package core

import (
	"testing"
	"unsafe"
)

func TestDevlinkAttrEnum(t *testing.T) {
	t.Run("size check", func(t *testing.T) {
		const expectedSizeInBytes = 1
		if sz := int(unsafe.Sizeof(DevlinkAttr(0))); sz != expectedSizeInBytes {
			t.Fatal("size mismatch")
		}
	})
	t.Run("value check", func(t *testing.T) {
		type TestData struct {
			actual DevlinkAttr
			expect DevlinkAttr
		}
		testData := []TestData{
			{actual: DevlinkAttrEnumUnspec, expect: 0},
			{actual: DevlinkAttrEnumBusName, expect: 1},
			{actual: DevlinkAttrEnumDevName, expect: 2},
			{actual: DevlinkAttrEnumPortIndex, expect: 3},
			{actual: DevlinkAttrEnumPortType, expect: 4},
			{actual: DevlinkAttrEnumPortDesiredType, expect: 5},
			{actual: DevlinkAttrEnumPortNetdevIfindex, expect: 6},
			{actual: DevlinkAttrEnumPortNetdevName, expect: 7},
			{actual: DevlinkAttrEnumPortIbdevName, expect: 8},
			{actual: DevlinkAttrEnumPortSplitCount, expect: 9},
			{actual: DevlinkAttrEnumPortSplitGroup, expect: 10},
			{actual: DevlinkAttrEnumSbIndex, expect: 11},
			{actual: DevlinkAttrEnumSbSize, expect: 12},
			{actual: DevlinkAttrEnumSbIngressPoolCount, expect: 13},
			{actual: DevlinkAttrEnumSbEgressPoolCount, expect: 14},
			{actual: DevlinkAttrEnumSbIngressTcCount, expect: 15},
			{actual: DevlinkAttrEnumSbEgressTcCount, expect: 16},
			{actual: DevlinkAttrEnumSbPoolIndex, expect: 17},
			{actual: DevlinkAttrEnumSbPoolType, expect: 18},
			{actual: DevlinkAttrEnumSbPoolSize, expect: 19},
			{actual: DevlinkAttrEnumSbPoolThresholdType, expect: 20},
			{actual: DevlinkAttrEnumSbThreshold, expect: 21},
			{actual: DevlinkAttrEnumSbTcIndex, expect: 22},
			{actual: DevlinkAttrEnumSbOccCur, expect: 23},
			{actual: DevlinkAttrEnumSbOccMax, expect: 24},
			{actual: DevlinkAttrEnumEswitchMode, expect: 25},
			{actual: DevlinkAttrEnumEswitchInlineMode, expect: 26},
			{actual: DevlinkAttrEnumDpipeTables, expect: 27},
			{actual: DevlinkAttrEnumDpipeTable, expect: 28},
			{actual: DevlinkAttrEnumDpipeTableName, expect: 29},
			{actual: DevlinkAttrEnumDpipeTableSize, expect: 30},
			{actual: DevlinkAttrEnumDpipeTableMatches, expect: 31},
			{actual: DevlinkAttrEnumDpipeTableActions, expect: 32},
			{actual: DevlinkAttrEnumDpipeTableCountersEnabled, expect: 33},
			{actual: DevlinkAttrEnumDpipeEntries, expect: 34},
			{actual: DevlinkAttrEnumDpipeEntry, expect: 35},
			{actual: DevlinkAttrEnumDpipeEntryIndex, expect: 36},
			{actual: DevlinkAttrEnumDpipeEntryMatchValues, expect: 37},
			{actual: DevlinkAttrEnumDpipeEntryActionValues, expect: 38},
			{actual: DevlinkAttrEnumDpipeEntryCounter, expect: 39},
			{actual: DevlinkAttrEnumDpipeMatch, expect: 40},
			{actual: DevlinkAttrEnumDpipeMatchValue, expect: 41},
			{actual: DevlinkAttrEnumDpipeMatchType, expect: 42},
			{actual: DevlinkAttrEnumDpipeAction, expect: 43},
			{actual: DevlinkAttrEnumDpipeActionValue, expect: 44},
			{actual: DevlinkAttrEnumDpipeActionType, expect: 45},
			{actual: DevlinkAttrEnumDpipeValue, expect: 46},
			{actual: DevlinkAttrEnumDpipeValueMask, expect: 47},
			{actual: DevlinkAttrEnumDpipeValueMapping, expect: 48},
			{actual: DevlinkAttrEnumDpipeHeaders, expect: 49},
			{actual: DevlinkAttrEnumDpipeHeader, expect: 50},
			{actual: DevlinkAttrEnumDpipeHeaderName, expect: 51},
			{actual: DevlinkAttrEnumDpipeHeaderId, expect: 52},
			{actual: DevlinkAttrEnumDpipeHeaderFields, expect: 53},
			{actual: DevlinkAttrEnumDpipeHeaderGlobal, expect: 54},
			{actual: DevlinkAttrEnumDpipeHeaderIndex, expect: 55},
			{actual: DevlinkAttrEnumDpipeField, expect: 56},
			{actual: DevlinkAttrEnumDpipeFieldName, expect: 57},
			{actual: DevlinkAttrEnumDpipeFieldId, expect: 58},
			{actual: DevlinkAttrEnumDpipeFieldBitwidth, expect: 59},
			{actual: DevlinkAttrEnumDpipeFieldMappingType, expect: 60},
			{actual: DevlinkAttrEnumPad, expect: 61},
			{actual: DevlinkAttrEnumEswitchEncapMode, expect: 62},
			{actual: DevlinkAttrEnumResourceList, expect: 63},
			{actual: DevlinkAttrEnumResource, expect: 64},
			{actual: DevlinkAttrEnumResourceName, expect: 65},
			{actual: DevlinkAttrEnumResourceId, expect: 66},
			{actual: DevlinkAttrEnumResourceSize, expect: 67},
			{actual: DevlinkAttrEnumResourceSizeNew, expect: 68},
			{actual: DevlinkAttrEnumResourceSizeValid, expect: 69},
			{actual: DevlinkAttrEnumResourceSizeMin, expect: 70},
			{actual: DevlinkAttrEnumResourceSizeMax, expect: 71},
			{actual: DevlinkAttrEnumResourceSizeGran, expect: 72},
			{actual: DevlinkAttrEnumResourceUnit, expect: 73},
			{actual: DevlinkAttrEnumResourceOcc, expect: 74},
			{actual: DevlinkAttrEnumDpipeTableResourceId, expect: 75},
			{actual: DevlinkAttrEnumDpipeTableResourceUnits, expect: 76},
			{actual: DevlinkAttrEnumPortFlavour, expect: 77},
			{actual: DevlinkAttrEnumPortNumber, expect: 78},
			{actual: DevlinkAttrEnumPortSplitSubportNumber, expect: 79},
			{actual: DevlinkAttrEnumParam, expect: 80},
			{actual: DevlinkAttrEnumParamName, expect: 81},
			{actual: DevlinkAttrEnumParamGeneric, expect: 82},
			{actual: DevlinkAttrEnumParamType, expect: 83},
			{actual: DevlinkAttrEnumParamValuesList, expect: 84},
			{actual: DevlinkAttrEnumParamValue, expect: 85},
			{actual: DevlinkAttrEnumParamValueData, expect: 86},
			{actual: DevlinkAttrEnumParamValueCmode, expect: 87},
			{actual: DevlinkAttrEnumRegionName, expect: 88},
			{actual: DevlinkAttrEnumRegionSize, expect: 89},
			{actual: DevlinkAttrEnumRegionSnapshots, expect: 90},
			{actual: DevlinkAttrEnumRegionSnapshot, expect: 91},
			{actual: DevlinkAttrEnumRegionSnapshotId, expect: 92},
			{actual: DevlinkAttrEnumRegionChunks, expect: 93},
			{actual: DevlinkAttrEnumRegionChunk, expect: 94},
			{actual: DevlinkAttrEnumRegionChunkData, expect: 95},
			{actual: DevlinkAttrEnumRegionChunkAddr, expect: 96},
			{actual: DevlinkAttrEnumRegionChunkLen, expect: 97},
			{actual: DevlinkAttrEnumInfoDriverName, expect: 98},
			{actual: DevlinkAttrEnumInfoSerialNumber, expect: 99},
			{actual: DevlinkAttrEnumInfoVersionFixed, expect: 100},
			{actual: DevlinkAttrEnumInfoVersionRunning, expect: 101},
			{actual: DevlinkAttrEnumInfoVersionStored, expect: 102},
			{actual: DevlinkAttrEnumInfoVersionName, expect: 103},
			{actual: DevlinkAttrEnumInfoVersionValue, expect: 104},
			{actual: DevlinkAttrEnumSbPoolCellSize, expect: 105},
			{actual: DevlinkAttrEnumFmsg, expect: 106},
			{actual: DevlinkAttrEnumFmsgObjNestStart, expect: 107},
			{actual: DevlinkAttrEnumFmsgPairNestStart, expect: 108},
			{actual: DevlinkAttrEnumFmsgArrNestStart, expect: 109},
			{actual: DevlinkAttrEnumFmsgNestEnd, expect: 110},
			{actual: DevlinkAttrEnumFmsgObjName, expect: 111},
			{actual: DevlinkAttrEnumFmsgObjValueType, expect: 112},
			{actual: DevlinkAttrEnumFmsgObjValueData, expect: 113},
			{actual: DevlinkAttrEnumHealthReporter, expect: 114},
			{actual: DevlinkAttrEnumHealthReporterName, expect: 115},
			{actual: DevlinkAttrEnumHealthReporterState, expect: 116},
			{actual: DevlinkAttrEnumHealthReporterErrCount, expect: 117},
			{actual: DevlinkAttrEnumHealthReporterRecoverCount, expect: 118},
			{actual: DevlinkAttrEnumHealthReporterDumpTs, expect: 119},
			{actual: DevlinkAttrEnumHealthReporterGracefulPeriod, expect: 120},
			{actual: DevlinkAttrEnumHealthReporterAutoRecover, expect: 121},
			{actual: DevlinkAttrEnumFlashUpdateFileName, expect: 122},
			{actual: DevlinkAttrEnumFlashUpdateComponent, expect: 123},
			{actual: DevlinkAttrEnumFlashUpdateStatusMsg, expect: 124},
			{actual: DevlinkAttrEnumFlashUpdateStatusDone, expect: 125},
			{actual: DevlinkAttrEnumFlashUpdateStatusTotal, expect: 126},
			{actual: DevlinkAttrEnumPortPciPfNumber, expect: 127},
			{actual: DevlinkAttrEnumPortPciVfNumber, expect: 128},
			{actual: DevlinkAttrEnumStats, expect: 129},
			{actual: DevlinkAttrEnumTrapName, expect: 130},
			{actual: DevlinkAttrEnumTrapAction, expect: 131},
			{actual: DevlinkAttrEnumTrapType, expect: 132},
			{actual: DevlinkAttrEnumTrapGeneric, expect: 133},
			{actual: DevlinkAttrEnumTrapMetadata, expect: 134},
			{actual: DevlinkAttrEnumTrapGroupName, expect: 135},
			{actual: DevlinkAttrEnumReloadFailed, expect: 136},
			{actual: DevlinkAttrEnumHealthReporterDumpTsNs, expect: 137},
			{actual: DevlinkAttrEnumNetnsFd, expect: 138},
			{actual: DevlinkAttrEnumNetnsPid, expect: 139},
			{actual: DevlinkAttrEnumNetnsId, expect: 140},
			{actual: DevlinkAttrEnumHealthReporterAutoDump, expect: 141},
			{actual: DevlinkAttrEnumTrapPolicerId, expect: 142},
			{actual: DevlinkAttrEnumTrapPolicerRate, expect: 143},
			{actual: DevlinkAttrEnumTrapPolicerBurst, expect: 144},
			{actual: DevlinkAttrEnumPortFunction, expect: 145},
			{actual: DevlinkAttrEnumInfoBoardSerialNumber, expect: 146},
			{actual: DevlinkAttrEnumPortLanes, expect: 147},
			{actual: DevlinkAttrEnumPortSplittable, expect: 148},
			{actual: DevlinkAttrEnumPortExternal, expect: 149},
			{actual: DevlinkAttrEnumPortControllerNumber, expect: 150},
			{actual: DevlinkAttrEnumFlashUpdateStatusTimeout, expect: 151},
			{actual: DevlinkAttrEnumFlashUpdateOverwriteMask, expect: 152},
			{actual: DevlinkAttrEnumReloadAction, expect: 153},
			{actual: DevlinkAttrEnumReloadActionsPerformed, expect: 154},
			{actual: DevlinkAttrEnumReloadLimits, expect: 155},
			{actual: DevlinkAttrEnumDevStats, expect: 156},
			{actual: DevlinkAttrEnumReloadStats, expect: 157},
			{actual: DevlinkAttrEnumReloadStatsEntry, expect: 158},
			{actual: DevlinkAttrEnumReloadStatsLimit, expect: 159},
			{actual: DevlinkAttrEnumReloadStatsValue, expect: 160},
			{actual: DevlinkAttrEnumRemoteReloadStats, expect: 161},
			{actual: DevlinkAttrEnumReloadActionInfo, expect: 162},
			{actual: DevlinkAttrEnumReloadActionStats, expect: 163},
			{actual: DevlinkAttrEnumPortPciSfNumber, expect: 164},
			{actual: DevlinkAttrEnumRateType, expect: 165},
			{actual: DevlinkAttrEnumRateTxShare, expect: 166},
			{actual: DevlinkAttrEnumRateTxMax, expect: 167},
			{actual: DevlinkAttrEnumRateNodeName, expect: 168},
			{actual: DevlinkAttrEnumRateParentNodeName, expect: 169},
			{actual: DevlinkAttrEnumRegionMaxSnapshots, expect: 170},
			{actual: DevlinkAttrEnumLinecardIndex, expect: 171},
			{actual: DevlinkAttrEnumLinecardState, expect: 172},
			{actual: DevlinkAttrEnumLinecardType, expect: 173},
			{actual: DevlinkAttrEnumLinecardSupportedTypes, expect: 174},
			{actual: DevlinkAttrEnumNestedDevlink, expect: 175},
			{actual: DevlinkAttrEnumSelftests, expect: 176},
			{actual: DevlinkAttrEnumRateTxPriority, expect: 177},
			{actual: DevlinkAttrEnumRateTxWeight, expect: 178},
			{actual: DevlinkAttrEnumRegionDirect, expect: 179},
		}
		for _, v := range testData {
			if v.actual != v.expect {
				t.Fatalf("value mismatch. actual %v, expected %v", v.actual, v.expect)
			}
		}
	})
	t.Run("Verify max value", func(t *testing.T) {
		if int(DevlinkAttrEnumMax) != int(DevlinkAttrEnumRegionDirect) {
			t.Fatal("max value mismatch")
		}
	})
}
