package core

// Errors - https://cs.opensource.google/go/x/sys/+/refs/tags/v0.25.0:unix/zerrors_linux.go;l=3641
type Errors uintptr

const (
	E2BIG       = Errors(0x7)
	EACCES      = Errors(0xd)
	EAGAIN      = Errors(0xb)
	EBADF       = Errors(0x9)
	EBUSY       = Errors(0x10)
	ECHILD      = Errors(0xa)
	EDOM        = Errors(0x21)
	EEXIST      = Errors(0x11)
	EFAULT      = Errors(0xe)
	EFBIG       = Errors(0x1b)
	EINTR       = Errors(0x4)
	EINVAL      = Errors(0x16)
	EIO         = Errors(0x5)
	EISDIR      = Errors(0x15)
	EMFILE      = Errors(0x18)
	EMLINK      = Errors(0x1f)
	ENFILE      = Errors(0x17)
	ENODEV      = Errors(0x13)
	ENOENT      = Errors(0x2)
	ENOEXEC     = Errors(0x8)
	ENOMEM      = Errors(0xc)
	ENOSPC      = Errors(0x1c)
	ENOTBLK     = Errors(0xf)
	ENOTDIR     = Errors(0x14)
	ENOTTY      = Errors(0x19)
	ENXIO       = Errors(0x6)
	EPERM       = Errors(0x1)
	EPIPE       = Errors(0x20)
	ERANGE      = Errors(0x22)
	EROFS       = Errors(0x1e)
	ESPIPE      = Errors(0x1d)
	ESRCH       = Errors(0x3)
	ETXTBSY     = Errors(0x1a)
	EWOULDBLOCK = Errors(0xb)
	EXDEV       = Errors(0x12)
)
